# Generated by Django 4.2.16 on 2026-05-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True, verbose_name='ID Paciente')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='IMC')),
                ('imc_clasificacion', models.CharField(blank=True, choices=[('Bajo peso', 'Bajo peso'), ('Normal', 'Normal'), ('Sobrepeso', 'Sobrepeso'), ('Obesidad', 'Obesidad')], max_length=20, null=True, verbose_name='Clasificación IMC')),
                ('presion_sistolica', models.IntegerField(verbose_name='Presión Sistólica')),
                ('presion_diastolica', models.IntegerField(verbose_name='Presión Diastólica')),
                ('frecuencia_cardiaca', models.IntegerField(verbose_name='Frecuencia Cardíaca')),
                ('glucosa', models.FloatField(verbose_name='Glucosa')),
                ('colesterol', models.FloatField(verbose_name='Colesterol')),
                ('saturacion_oxigeno', models.FloatField(verbose_name='Saturación O₂')),
                ('temperatura', models.FloatField(verbose_name='Temperatura')),
                ('antecedentes_familiares', models.BooleanField(default=False, verbose_name='Antecedentes Familiares')),
                ('fumador', models.BooleanField(default=False, verbose_name='Fumador')),
                ('consumo_alcohol', models.BooleanField(default=False, verbose_name='Consumo Alcohol')),
                ('actividad_fisica', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20, verbose_name='Actividad Física')),
                ('diagnostico_preliminar', models.CharField(choices=[('Paciente sano', 'Paciente sano'), ('Prehipertensión', 'Prehipertensión'), ('Hipertensión', 'Hipertensión'), ('Diabetes Tipo 2', 'Diabetes Tipo 2'), ('Obesidad', 'Obesidad'), ('Riesgo cardiovascular', 'Riesgo cardiovascular'), ('Cardiopatía', 'Cardiopatía')], max_length=100, verbose_name='Diagnóstico Preliminar')),
                ('riesgo_enfermedad', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=20, verbose_name='Riesgo de Enfermedad')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha Consulta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('es_critico', models.BooleanField(default=False, verbose_name='Es Crítico')),
                ('es_hipertenso', models.BooleanField(default=False, verbose_name='Es Hipertenso')),
                ('es_diabetico', models.BooleanField(default=False, verbose_name='Es Diabético')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['riesgo_enfermedad'], name='pacientes_riesgo__a6e45b_idx'), models.Index(fields=['diagnostico_preliminar'], name='pacientes_diagnos_a4a997_idx'), models.Index(fields=['es_critico'], name='pacientes_es_crit_3af8d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ETLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('tiempo_ejecucion', models.FloatField(blank=True, null=True, verbose_name='Tiempo Ejecución (seg)')),
                ('fuente', models.CharField(choices=[('DATASET_BASE', 'Dataset Base'), ('CSV_UPLOAD', 'CSV Subido'), ('EXCEL_UPLOAD', 'Excel Subido'), ('GENERADO', 'Generado Automáticamente')], max_length=20, verbose_name='Fuente')),
                ('archivo_fuente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo Fuente')),
                ('registros_extraidos', models.IntegerField(default=0, verbose_name='Registros Extraídos')),
                ('registros_duplicados', models.IntegerField(default=0, verbose_name='Registros Duplicados')),
                ('registros_nulos', models.IntegerField(default=0, verbose_name='Registros con Nulos')),
                ('registros_invalidos', models.IntegerField(default=0, verbose_name='Registros Inválidos')),
                ('registros_cargados', models.IntegerField(default=0, verbose_name='Registros Cargados')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('log_detalle', models.TextField(blank=True, verbose_name='Log Detallado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje Error')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_processes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial ETL',
                'verbose_name_plural': 'Historial ETL',
                'db_table': 'etl_history',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
