# Generated by Django 4.2.16 on 2026-05-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_entrada', models.JSONField()),
                ('riesgo_predicho', models.CharField(max_length=20)),
                ('confianza', models.FloatField()),
                ('probabilidades', models.JSONField()),
                ('modelo_usado', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_predicciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('random_forest', 'Random Forest'), ('logistic_regression', 'Regresión Logística'), ('decision_tree', 'Árbol de Decisión')], max_length=30)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('total_samples', models.IntegerField(default=0)),
                ('train_samples', models.IntegerField(default=0)),
                ('test_samples', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
